#!/bin/bash

# 定义域名列表
DOMAINS=(
    "www1.szu.edu.cn"
    "ehall.szu.edu.cn"
    "ms.szu.edu.cn"
)

# 定义 IP 地址列表
IPS=(
    "172.30.255.42"
)

# 创建 IP 集配置文件
CONFIG_FILE="ipset_szu.txt"
echo "# Generated by ipset-automation" > $CONFIG_FILE
echo "create szuip hash:ip family inet hashsize 1024 maxelem 65536" >> $CONFIG_FILE

# 解析域名并添加到配置文件
for DOMAIN in "${DOMAINS[@]}"; do
    IP=$(dig +short $DOMAIN)
    if [ -n "$IP" ]; then
        echo "add szuip $IP" >> $CONFIG_FILE
        echo "Added $IP from $DOMAIN to szuip IP set"
    else
        echo "Failed to resolve $DOMAIN"
    fi
done

# 添加固定 IP 地址到配置文件
for IP in "${IPS[@]}"; do
    echo "add szuip $IP" >> $CONFIG_FILE
    echo "Added $IP to szuip IP set"
done

echo "IP set configuration file generated: $CONFIG_FILE"
