name: Generate IPSet Config

on:
  push:
    branches:
      - main

jobs:
  generate-config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.0

    - name: Generate IPSet Config
      run: |
        chmod +x generate.sh
        ./generate.sh

    - name: Upload IPSet Config
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: ipset_szu
        path: downloads/ipset_szu.txt
